<?php
$author = setting('author', app_config('author'));
$themeColor = setting('theme_color', app_config('theme_color'));
$desc = $pageDescription ?? setting('description_default', app_config('description_default'));
?><meta charset="UTF-8"><meta http-equiv="Cache-Control" content="no-siteapp"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="referrer" content="origin-when-cross-origin"><meta name="robots" content="index,follow"><meta name="page-generated" content="<?php echo e(date('Y-m-d H:i:s T')); ?>"><meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta name="format-detection" content="telephone=no,email=no"><meta name="google" content="notranslate"><meta name="author" content="<?php echo e($author); ?>"><meta name="theme-color" content="<?php echo e($themeColor); ?>"><meta name="description" content="<?php echo e($desc); ?>">
